# Generated by Django 4.2.1 on 2023-06-13 07:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_title', models.CharField(max_length=200)),
                ('pin_body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.CharField(max_length=200)),
                ('pin_image', models.ImageField(blank=True, null=True, upload_to='images/pin_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_pic', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('e_posta', models.EmailField(max_length=250)),
                ('bio', models.TextField(blank=True, null=True)),
                ('follower', models.ManyToManyField(blank=True, null=True, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='İmage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.CharField(max_length=200)),
                ('post_date', models.DateField(auto_now_add=True, null=True)),
                ('snippet', models.CharField(blank=True, max_length=250, null=True)),
                ('likes', models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
